### ISSUE TITLE
Ask for explanation

### ISSUE THREAD

**Issue by tarnh** [sugiyamath/extractor_workflow#1]
Hi Sugiya,

 sadly I can't read https://datanerd.hateblo.jp/entry/2019/12/02/121945 as a foreigner.

May you please explain what you are doing with ParaCrawl? Only finding Japanese texts?

**Comment by sugiyamath** [comment]
Hi @tarnh .

Actually, we've tried to create japanese-english parallel corpus by using bitextor.
According to NTT's paper, they use paracrawl/extractor to select candidates, and we want to try it.
https://arxiv.org/abs/1911.10668

In short, we want to create a large size parallel corpus like JParaCrawl by ourselves.
